/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ComprarController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author unifaljesus
 */
public class ComprarUsuarioFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComprarUsuarioFrame
     */
    public ComprarUsuarioFrame(Usuario usuario) {
        initComponents();
        c = new ComprarController(this, usuario);
    }

    public ComprarController getC() {
        return c;
    }

    public void setC(ComprarController c) {
        this.c = c;
    }

    public JButton getBtAcessarComprar() {
        return btAcessarComprar;
    }

    public void setBtAcessarComprar(JButton btAcessarComprar) {
        this.btAcessarComprar = btAcessarComprar;
    }

    public JButton getBtComprarBit() {
        return btComprarBit;
    }

    public void setBtComprarBit(JButton btComprarBit) {
        this.btComprarBit = btComprarBit;
    }

    public JButton getBtComprarEthe() {
        return btComprarEthe;
    }

    public void setBtComprarEthe(JButton btComprarEthe) {
        this.btComprarEthe = btComprarEthe;
    }

    public JButton getBtComprarRip() {
        return btComprarRip;
    }

    public void setBtComprarRip(JButton btComprarRip) {
        this.btComprarRip = btComprarRip;
    }

    public JLabel getLblBit() {
        return lblBit;
    }

    public void setLblBit(JLabel lblBit) {
        this.lblBit = lblBit;
    }

    public JLabel getLblComprar() {
        return lblComprar;
    }

    public void setLblComprar(JLabel lblComprar) {
        this.lblComprar = lblComprar;
    }

    public JLabel getLblEthe() {
        return lblEthe;
    }

    public void setLblEthe(JLabel lblEthe) {
        this.lblEthe = lblEthe;
    }

    public JLabel getLblRip() {
        return lblRip;
    }

    public void setLblRip(JLabel lblRip) {
        this.lblRip = lblRip;
    }

    public JLabel getLblSenhaComprar() {
        return lblSenhaComprar;
    }

    public void setLblSenhaComprar(JLabel lblSenhaComprar) {
        this.lblSenhaComprar = lblSenhaComprar;
    }

    public JPasswordField getPwdComprar() {
        return pwdComprar;
    }

    public void setPwdComprar(JPasswordField pwdComprar) {
        this.pwdComprar = pwdComprar;
    }

    public JTextField getTxtCotBitcoin() {
        return txtCotBitcoin;
    }

    public void setTxtCotBitcoin(JTextField txtCotBitcoin) {
        this.txtCotBitcoin = txtCotBitcoin;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getTxtCotEthereum() {
        return txtCotEthereum;
    }

    public void setTxtCotEthereum(JTextField txtCotEthereum) {
        this.txtCotEthereum = txtCotEthereum;
    }

    public JTextField getTxtCotRipple() {
        return txtCotRipple;
    }

    public void setTxtCotRipple(JTextField txtCotRipple) {
        this.txtCotRipple = txtCotRipple;
    }

    public JTextField getTxtQuantBitcoin() {
        return txtQuantBitcoin;
    }

    public void setTxtQuantBitcoin(JTextField txtQuantBitcoin) {
        this.txtQuantBitcoin = txtQuantBitcoin;
    }

    public JTextField getTxtQuantEthereum() {
        return txtQuantEthereum;
    }

    public void setTxtQuantEthereum(JTextField txtQuantEthereum) {
        this.txtQuantEthereum = txtQuantEthereum;
    }

    public JTextField getTxtQuantRipple() {
        return txtQuantRipple;
    }

    public void setTxtQuantRipple(JTextField txtQuantRipple) {
        this.txtQuantRipple = txtQuantRipple;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAcessarComprar = new javax.swing.JButton();
        btComprarBit = new javax.swing.JButton();
        btComprarEthe = new javax.swing.JButton();
        btComprarRip = new javax.swing.JButton();
        lblComprar = new javax.swing.JLabel();
        pwdComprar = new javax.swing.JPasswordField();
        lblSenhaComprar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantBitcoin = new javax.swing.JTextField();
        txtQuantEthereum = new javax.swing.JTextField();
        txtQuantRipple = new javax.swing.JTextField();
        txtCotBitcoin = new javax.swing.JTextField();
        txtCotEthereum = new javax.swing.JTextField();
        txtCotRipple = new javax.swing.JTextField();
        lblBit = new javax.swing.JLabel();
        lblEthe = new javax.swing.JLabel();
        lblRip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXCHANGE DE CRIPTOMOEDAS");
        setPreferredSize(new java.awt.Dimension(1300, 600));

        jPanel1.setBackground(new java.awt.Color(106, 48, 103));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 600));

        btAcessarComprar.setBackground(new java.awt.Color(134, 75, 131));
        btAcessarComprar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btAcessarComprar.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarComprar.setText("Acessar");
        btAcessarComprar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAcessarComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarComprarActionPerformed(evt);
            }
        });

        btComprarBit.setBackground(new java.awt.Color(134, 75, 131));
        btComprarBit.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btComprarBit.setForeground(new java.awt.Color(255, 255, 255));
        btComprarBit.setText("Comprar");
        btComprarBit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btComprarBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarBitActionPerformed(evt);
            }
        });

        btComprarEthe.setBackground(new java.awt.Color(134, 75, 131));
        btComprarEthe.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btComprarEthe.setForeground(new java.awt.Color(255, 255, 255));
        btComprarEthe.setText("Comprar");
        btComprarEthe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btComprarEthe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarEtheActionPerformed(evt);
            }
        });

        btComprarRip.setBackground(new java.awt.Color(134, 75, 131));
        btComprarRip.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btComprarRip.setForeground(new java.awt.Color(255, 255, 255));
        btComprarRip.setText("Comprar");
        btComprarRip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btComprarRip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarRipActionPerformed(evt);
            }
        });

        lblComprar.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblComprar.setForeground(new java.awt.Color(255, 255, 255));
        lblComprar.setText("COMPRAR CRIPTOMOEDAS");

        lblSenhaComprar.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblSenhaComprar.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhaComprar.setText("Senha:");

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantidade:");

        lblBit.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblBit.setForeground(new java.awt.Color(255, 255, 255));
        lblBit.setText("Cotação Bitcoin:");

        lblEthe.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblEthe.setForeground(new java.awt.Color(255, 255, 255));
        lblEthe.setText("Cotação Ethereum:");

        lblRip.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        lblRip.setForeground(new java.awt.Color(255, 255, 255));
        lblRip.setText("Cotação Ripple:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(lblComprar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(lblSenhaComprar)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEthe, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblBit, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRip, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdComprar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCotBitcoin, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txtCotEthereum, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(158, 158, 158)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtQuantBitcoin))))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btComprarBit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAcessarComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCotRipple, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtQuantRipple)
                            .addComponent(txtQuantEthereum, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btComprarEthe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btComprarRip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(291, 291, 291))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblComprar)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaComprar)
                    .addComponent(pwdComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAcessarComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btComprarBit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCotBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantEthereum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btComprarEthe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCotEthereum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEthe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btComprarRip, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantRipple, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCotRipple, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAcessarComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarComprarActionPerformed
//        MenuUsuarioFrame musuario = new MenuUsuarioFrame();
//        musuario.setVisible(true);
        c.comprarCriptomoeda();
    }//GEN-LAST:event_btAcessarComprarActionPerformed

    private void btComprarBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarBitActionPerformed
        c.comprarBitcoin();
    }//GEN-LAST:event_btComprarBitActionPerformed

    private void btComprarEtheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarEtheActionPerformed
        c.comprarEthereum();
    }//GEN-LAST:event_btComprarEtheActionPerformed

    private void btComprarRipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarRipActionPerformed
        c.comprarRipple();
    }//GEN-LAST:event_btComprarRipActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ComprarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ComprarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ComprarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ComprarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ComprarUsuarioFrame().setVisible(true);
//            }
//        });
//    }

    private ComprarController c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarComprar;
    private javax.swing.JButton btComprarBit;
    private javax.swing.JButton btComprarEthe;
    private javax.swing.JButton btComprarRip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBit;
    private javax.swing.JLabel lblComprar;
    private javax.swing.JLabel lblEthe;
    private javax.swing.JLabel lblRip;
    private javax.swing.JLabel lblSenhaComprar;
    private javax.swing.JPasswordField pwdComprar;
    private javax.swing.JTextField txtCotBitcoin;
    private javax.swing.JTextField txtCotEthereum;
    private javax.swing.JTextField txtCotRipple;
    private javax.swing.JTextField txtQuantBitcoin;
    private javax.swing.JTextField txtQuantEthereum;
    private javax.swing.JTextField txtQuantRipple;
    // End of variables declaration//GEN-END:variables
}
